services:
  web:
    container_name: reflex
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - REFLEX_ENV=dev
      - DATABASE_URL=sqlite:///data/database.db
      - PYTHONPATH=/app
    networks:
      - tradesim
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:

networks:
  tradesim:
    driver: bridge