services:
  web:
    container_name: reflex # Mantenemos el nombre del contenedor si lo prefieres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      # - .:/app # <-- LÍNEA ELIMINADA O COMENTADA - ¡IMPORTANTE!
      - sqlite_data:/app/data # Montaje solo para la base de datos persistente
    environment:
      - REFLEX_ENV=dev # O prod si lo prefieres para la ejecución normal
      - DATABASE_URL=sqlite:///data/tradesim.db # Ruta DENTRO del contenedor
      - PYTHONUNBUFFERED=1 # Para que los logs salgan directos
      - PYTHONPATH=/app # Para asegurar que Python encuentre tus módulos
    networks:
      - tradesim
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data: # Define el volumen nombrado para persistir la BBDD

networks:
  tradesim:
    driver: bridge