"""empty message

Revision ID: 6ced14d42914
Revises: b629758e191d
Create Date: 2025-02-11 16:36:27.167235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ced14d42914'
down_revision: Union[str, None] = 'b629758e191d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localauthsession', schema=None) as batch_op:
        batch_op.drop_index('ix_localauthsession_session_id')
        batch_op.drop_index('ix_localauthsession_user_id')

    op.drop_table('localauthsession')
    with op.batch_alter_table('localuser', schema=None) as batch_op:
        batch_op.drop_index('ix_localuser_username')

    op.drop_table('localuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.BLOB(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('localuser', schema=None) as batch_op:
        batch_op.create_index('ix_localuser_username', ['username'], unique=1)

    op.create_table('localauthsession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('expiration', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('localauthsession', schema=None) as batch_op:
        batch_op.create_index('ix_localauthsession_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_localauthsession_session_id', ['session_id'], unique=1)

    # ### end Alembic commands ###
